### ISSUE TITLE
Inlining fails

### ISSUE THREAD

**Issue by thorade** [casella/FailureModes#2]
Some (or all?) tools fail to inline models that use intermediate protected variables, so the function does not get inlined, without a warning or message to the user. 
Another case that is easy to rewrite is described here:
https://github.com/xogeny/ModelicaBook/issues/338

Is testing/improving such behavior within the scope of this library?
If yes, I could provide some examples of functions that do not get inlined, but could be rewritten easily.

**Comment by casella** [comment]
My idea for this library was to focus on run-time errors, not on compilation-time issues. BTW, in most cases, failure to inline only leads to degraded performance, but is not necessarily an error.

**Comment by johanrhodin** [comment]
Nothing in the `Readme` says that compilation-time issues are not welcome. In general I think it would be nice to have compilation-time issues too since the user can be just as confused by them (with cryptic or totally missing warnings) as for run-time errors.
.

**Comment by casella** [comment]
I tried to improve the `Readme` to better clarify the current scope of the library.

As far as I understand, although on some issues (e.g. convergence of nonlinear solvers) some tools may be smarter than others and avoid some runtime errors, all the test cases in this library are basically tool-independent, because they don't reveal errors in the way the tool handles the model, but rather inherent issues with the models themselves, i.e., with their equations.

I am afraid that compilation-time issues will be a lot more tool-specific, and also sometimes questionable. For example, regarding inlining, the specification of the Inline annotation says " the model developer proposes to inline the function". I think not inlining it is possibly a matter of quality of implementation, but definitely not a failure.

That said, if you have other ideas I would encourage you to open another issue on GitHub and discuss them there. For instance, you could start compiling a list of issues that may be reported in a cryptic way and how they should reported instead. If there is enough material for another library, or for an extension of this library, I'd be happy to work on that.
