### ISSUE TITLE
Update library denpendence to MSL v4.0.0?

### ISSUE THREAD

**Issue by Satinelamp** [casella/FailureModes#5]
MSL v4.0.0 renamed Modelica.SIUnits to Modelica.Units, in Dymola 2021X, MSL v4.0.0 is already available, maybe a new release version of this library would be worth considering. But this library just imports Modelica.SIUnits at the top level, so a trivial modification should also work fine.

**Comment by casella** [comment]
Going to MSL 4.0.0 is an irreversible move, unless one wants to keep both a 3.2.3 and a 4.0.0 branches active, which is probably just a waste of time. Dymola supports MSL 4.0.0 since November, OpenModelica is working on that, but full support will only be available with 1.18.0 next July. 

I don't see a major need to exploit MSL 4.0.0 features in FailureModes, so I'd wait until the release of OpenModelica 1.18.0 next summer, when proper package management will be available in the tool. The plan is to have long-term maintenance for 3.2.3, and the library is standalone, so I don't see any reason to rush.
